// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/anuragchauhan766/to-do-golang-htmx/view/layout"
import "github.com/anuragchauhan766/to-do-golang-htmx/view/components"
import "github.com/anuragchauhan766/to-do-golang-htmx/model"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"w-full h-screen bg-primary flex items-center justify-center\"><div class=\"max-w-screen-md w-full h-full p-10\"><div class=\"w-full h-full bg-secondary rounded-lg flex p-10 flex-col items-center gap-4\"><h1 class=\"text-3xl text-ctc font-extrabold\"><i class=\"fa-solid fa-square-check text-ctc\"></i> <span>My Todo</span></h1><hr class=\"h-1 bg-primary border-none rounded-lg w-full\"><div class=\"flex flex-col gap-4 py-4 items-center w-full justify-center\"><form hx-post=\"/api/v1/todo\" class=\"w-3/4 text-lg font-bold rounded-lg flex items-center justify-center\" hx-target=\"#todoContainer\" hx-on::after-request=\"this.reset()\"><input type=\"text\" placeholder=\"Add items...\" class=\"h-14 w-3/4 text-black appearance-none outline-none border-none ring-0 focus:ring-0 focus:ring-transparent border-4 border-ctc focus:border-ctc py-3 px-4 rounded-l-lg placeholder:text-gray-400\" name=\"todoContent\"> <button type=\"submit\" class=\"h-14 w-1/4 text-white bg-ctc hover:bg-ctc-light rounded-r-lg p-2\">Add</button></form><div class=\"flex flex-col gap-4 items-center w-full justify-center\" id=\"todoContainer\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, value := range model.Todos {
				templ_7745c5c3_Err = components.TodoCard(value).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Index().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
